name: bikeblog
recipe: drupal10
config:
  webroot: web

services:
  pma:
    type: phpmyadmin
    hosts:
      - database

proxy:
  appserver:
    - bikeblog.lndo.site
  pma:
    - bikeblog-db.lndo.site
