name: trainer
recipe: drupal10
config:
  webroot: web

services:
  pma:
    type: phpmyadmin
    hosts:
      - database

proxy:
  appserver:
    - trainer.lndo.site
  pma:
    - trainer-db.lndo.site
